name: CodeCaffe Lambda Function
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: "Deploy Code to AWS"
        uses: appleboy/lambda-action@master
        with:
          aws_region: ${{secrets.AWS_REGION}}
          aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_KEY}}
          function_name: CodeCaffe
          zip_file: bundle.zip
