name: CodeCaffe Lambda Function
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
      - name: Publish SNS Topic
        uses: nothingalike/sns-publish-topic@v1.7
        with:
          MESSAGE: "message"
          TOPIC_ARN: $ {{ secrets.SNS_TOPIC }}
        env: 
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: $ {{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: $ {{ secrets.SECRET_ACCESS_KEY }}
    
